### ISSUE TITLE
Deploy a sequence of Issuers and a Verifier for the ISED Business Banking Initiative Flow

### ISSUE THREAD

**Issue by swcurran** [bcgov/essential-services-delivery#84]
<This is a work in progress -- details are still being added>

We need to deploy three standard issuers and a verifier in sequence as a stand in for the BC Registries issuer as part of the ISED Business Banking Initiative.  That initiative has a business owner receiving three credentials about their business from BC Registries and then using those credentials to open a business bank account.

~@esune -- I'll describe this using features we have today, but something to consider.  Can we have the issuing happen from a single issuer using the same connection?  No problem if not, but that would be neat :-)~

The flow we'll be using is the following:

* Use the test services card to get into a "BC registries verified person" credential
* Use the "BC Registries verified person" VC to get a "registration" credential (about the business)
* Use the "BC Registries verified person" and the "registration" credential to get a "Verified Relationship" credential (the person to the business)
* Have "Visual Verifier" for the Bank that checks for all three VCs -- all data

The VCs we can start with are all defined here: https://github.com/bcgov/von-bc-registries-agent/blob/master/bcreg-aca/config/schemas.yml.  We want to use:

- demo.verified_person.registries.ca
- registration.registries.ca
- demo.person_relationship.registries.ca

For a first cut, the Visual Verifier can grab interesting ones from all three -- registration_id, entity_name, entity_status (registration), First Name, Last Name, email address, phone number (verfied person) and Registration ID, Associated registration name, relationship_description, relationship_status (verified person relationship).

**Comment by esune** [comment]
> 
> @esune -- I'll describe this using features we have today, but something to consider. Can we have the issuing happen from a single issuer using the same connection? No problem if not, but that would be neat :-)

We would need to update the codebase in `issuer-kit` to:
- implement the proposed connection-aware pattern described [here](https://hackmd.io/@esune/B1DFUwEoP)
- understand if it is possible to implement the above pattern to support the same issuer using different frontends: cookies are set for each domain and the two BC Registries credentials will require two separate frontends to be issued, since their schemas/input forms will be different.

**Comment by esune** [comment]
Issuers:
- https://bcreg-issuer-dev.pathfinder.gov.bc.ca
- https://bcreg-registration-issuer-dev.pathfinder.gov.bc.ca
- https://bcreg-relationship-issuer-dev.pathfinder.gov.bc.ca

Verifier: 
- https://bcbank-verifier-dev.pathfinder.gov.bc.ca
