### ISSUE TITLE
Update Visual Verifier deployment configurations

### ISSUE THREAD

**Issue by esune** [bcgov/essential-services-delivery#87]
Following the recent updates to [vc-visual-verifier](https://github.com/bcgov/vc-visual-verifier/pull/12), we should update the deployment configurations so that content from a configmap can be mounted on the container to customize the landing page.

The pattern to follow would be similar to what we already do for the components deployed using `issuer-kit` code, allowing the overrides to be defined by profile.

**Comment by swcurran** [comment]
Please add a least one example and point me to it, and we'll add some docs to some of the verifiers.

Thanks!

**Comment by esune** [comment]
> 
> 
> Please add a least one example and point me to it, and we'll add some docs to some of the verifiers.
> 
> Thanks!

Will do once we have the updated configurations in the repository!
