### ISSUE TITLE
Deploy services to prod

### ISSUE THREAD

**Issue by esune** [bcgov/essential-services-delivery#99]
The services need to be deployed to the `prod` namespace.

Wallets need to be migrated over from the OCP3 namespace, and for services using a `*.vonx.io` vanity URL DNS migration and certificate installation needs to be performed as well.

@wadeking98 please proceed with deploying all the issuers in `read only` mode, using the wallets and secret values from OCP3.
Once ready, coordinate with @WadeBarnes to add the `vonx.io` routes and certificates, and switch the DNS entry to point to the new cluster.

**Comment by wadeking98** [comment]
up and running in OCP4
